name: SuperTeams
version: 1.0.0
main: discord.qeid.Teams
description: A multi-functional SMP based Teams plugin, featuring efficient SQLite storing, configurable messages, and more.
api-version: 1.21
author: qeid
website: https://github.com/qeid/SuperTeams
dependencies:
  server:
    PlaceholderAPI:
      # Load order is relative to the dependency. So here PlaceholderAPI loads before our plugin.
      load: BEFORE
      required: false